CREATE TABLE BANK(
  BANK_NAME VARCHAR(50) NOT NULL,
  BANK_CODE INT PRIMARY KEY IDENTITY(1,1),
  ADDRESS VARCHAR(100) NOT NULL
  
);

INSERT INTO BANK VALUES('SBI','RAJPATH');
INSERT INTO BANK VALUES('HDFC','NAYAPALLI');
INSERT INTO BANK VALUES('AXIS','SAHEED NAGAR');

CREATE TABLE BRANCH(
  BRANCH_ID INT PRIMARY KEY IDENTITY(1,1),
  BRANCH_NAME VARCHAR(100) UNIQUE,
  ADDRESS VARCHAR(100) NOT NULL,
  BANK_CODE INT FOREIGN KEY REFERENCES BANK(BANK_CODE) ON DELETE CASCADE
);

INSERT INTO BRANCH VALUES("RAJPATH","RAJPATH",1)
INSERT INTO BRANCH VALUES("NAYAPALLI","NAYAPALLI",2)
INSERT INTO BRANCH VALUES("SAHEED NAGAR","SAHEED NAGAR",3)

CREATE TABLE CUSTOMER(
  CUSTOMER_ID INT PRIMARY KEY IDENTITY(1,1),
  NAME VARCHAR(50) NOT NULL,
  PHONE_NO BIGINT  NOT NULL,
  ADDRESS VARCHAR(100) NOT NULL,
)


INSERT INTO CUSTOMER VALUES("SASWAT","1234567890","KALINGA STADIUM");
INSERT INTO CUSTOMER VALUES("SAI","1234567890","BHADRAK");
INSERT INTO CUSTOMER VALUES("SWASTIK","1234567890","DHENKANAL");
INSERT INTO CUSTOMER VALUES("PIYUSH","1234567890","NIMAPADA");
INSERT INTO CUSTOMER VALUES("JANMEJAYA","1234567890","CUTTACK");


CREATE TABLE ACCOUNT(
  ACCOUNT_NO INT PRIMARY KEY IDENTITY(1,1),
  ACCOUNT_TYPE VARCHAR(100) NOT NULL,
  BALANCE BIGINT NOT NULL,
  BRANCH_ID INT FOREIGN KEY REFERENCES BRANCH(BRANCH_ID) ON UPDATE CASCADE
);

INSERT INTO ACCOUNT VALUES("SAVING","100000",1);
INSERT INTO ACCOUNT VALUES("CURRENT","1000000",1);
INSERT INTO ACCOUNT VALUES("SAVING","1200000",2);
INSERT INTO ACCOUNT VALUES("SALARY","2100000",3);


CREATE TABLE LOAN(
  LOAN_ID INT PRIMARY KEY IDENTITY(1,1),
  LOAN_TYPE VARCHAR(10) CHECK (LOAN_TYPE IN('PL','HL')),
  AMOUNT BIGINT NOT NULL,
  BRANCH_ID INT FOREIGN KEY REFERENCES BRANCH(BRANCH_ID)
);

INSERT INTO LOAN VALUES('PL',1000000,1)
INSERT INTO LOAN VALUES('PL',1020000,2)
INSERT INTO LOAN VALUES('HL',8000000,3)

SELECT * FROM BANK;
SELECT * FROM BRANCH;
SELECT * FROM CUSTOMER;
SELECT * FROM ACCOUNT;
SELECT * FROM LOAN;
